// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using intranet.Models;

namespace intranet.Migrations
{
    [DbContext(typeof(TableroContext))]
    partial class TableroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("intranet.Models.Procesos", b =>
                {
                    b.Property<int>("Id_Proceso")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fuente");

                    b.Property<string>("Numeral");

                    b.Property<string>("Observacion");

                    b.Property<string>("Proceso");

                    b.Property<int?>("ProcesosId_Proceso");

                    b.Property<string>("Unidad");

                    b.HasKey("Id_Proceso");

                    b.HasIndex("ProcesosId_Proceso");

                    b.ToTable("Procesos");
                });

            modelBuilder.Entity("intranet.Models.Registros", b =>
                {
                    b.Property<int>("Id_Registro")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Denominador");

                    b.Property<float>("Indicador");

                    b.Property<float>("Meta");

                    b.Property<float>("Numerador");

                    b.Property<string>("Periodo");

                    b.Property<int>("ProcesoId");

                    b.Property<int?>("Reg_ProcesoId_Proceso");

                    b.HasKey("Id_Registro");

                    b.HasIndex("Reg_ProcesoId_Proceso");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("intranet.Models.Procesos", b =>
                {
                    b.HasOne("intranet.Models.Procesos")
                        .WithMany("List_Procesos")
                        .HasForeignKey("ProcesosId_Proceso");
                });

            modelBuilder.Entity("intranet.Models.Registros", b =>
                {
                    b.HasOne("intranet.Models.Procesos", "Reg_Proceso")
                        .WithMany()
                        .HasForeignKey("Reg_ProcesoId_Proceso");
                });
#pragma warning restore 612, 618
        }
    }
}
